config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.views import defaults as default_views

from dream_blog.feeds import RssFeed
from dream_blog.sitemaps import SITEMAPS

urlpatterns = [
    path("sitemap.xml", sitemap, {"sitemaps": SITEMAPS}, name="sitemap"),
    path("rss.xml", RssFeed(), name="rss"),
    path("", include("dream_blog.urls")),
    path("posts/", include("posts.urls")),
    path("tutorials/", include("tutorials.urls")),
    path("columns/", include("columns.urls")),
    path("comments/", include("comments.urls")),
    path("accounts/", include("allauth.urls")),
    path("markdown-field/", include("markdown_field.urls")),
    path("ht/", include("health_check.urls")),
    path("webtools/", include("webtools.urls")),
    path("notifications/", include("notify.urls")),
    path("notifications/", include("notifications.urls")),
    path(settings.ADMIN_URL, admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

    if "django_browser_reload" in settings.INSTALLED_APPS:
        urlpatterns = [
            path("__reload__/", include("django_browser_reload.urls"))
        ] + urlpatterns

dream_blog/comments/urls.py
from comments.views import CommentFormTemplateView, CommentPostView
from django.urls import path

app_name = "comments"
urlpatterns = [
    path("form/", CommentFormTemplateView.as_view(), name="form"),
    path("post/", CommentPostView.as_view(), name="post"),
]

dream_blog/notify/urls.py
from django.urls import path

from . import views

app_name = "notify"
urlpatterns = [
    path("", views.AllNotificationsListView.as_view(), name="notification_all"),
    path(
        "unread/",
        views.UnreadNotificationsListView.as_view(),
        name="notification_unread",
    ),
]

dream_blog/posts/urls.py
from django.urls import path
from posts import views

app_name = "posts"
urlpatterns = [
    path("<int:pk>/", views.PostDetailView.as_view(), name="detail"),
]

dream_blog/urls.py
from django.urls import path

from dream_blog.views import HomeView

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
]

dream_blog/columns/views.py
from columns.models import Article, Column
from core.views import SetHeadlineMixin
from hitcount.views import HitCountDetailView


class ColumnDetailView(SetHeadlineMixin, HitCountDetailView):
    model = Column
    count_hit = True
    template_name = "columns/detail.html"

    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)
        return response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        articles = self.object.article_set.visible().order_by("-publish_date")
        context["articles"] = articles
        return context

    def get_queryset(self):
        return Column.objects.visible().order_by("-created_at")

    def get_headline(self):
        return self.object.title


class ArticleDetailView(SetHeadlineMixin, HitCountDetailView):
    model = Article
    count_hit = True
    template_name = "columns/article_detail.html"

    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)
        return response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def get_queryset(self):
        return (
            Article.objects.visible()
            .select_related("column")
            .order_by("-publish_date")
            .with_comment_count()
        )

    def get_headline(self):
        return f"{self.object.title} - {self.object.column.title}"

dream_blog/comments/views.py
import functools

from comments import get_form
from django.apps import apps
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.http.response import HttpResponse as HttpResponse
from django.utils.decorators import method_decorator
from django.utils.html import escape
from django.views.decorators.csrf import csrf_protect
from django.views.generic import FormView, TemplateView
from tree_comments import signals
from tree_comments.views import CommentPostBadRequest


def inject_comment_target(func):
    @functools.wraps(func)
    def wrapper(view, *args, **kwargs):
        request = view.request
        if request.method.upper() == "POST":
            ctype = request.POST.get("content_type")
            object_pk = request.POST.get("object_pk")
        else:
            ctype = request.GET.get("content_type")
            object_pk = request.GET.get("object_pk")

        if ctype is None or object_pk is None:
            return CommentPostBadRequest("Missing content_type or object_pk field.")

        try:
            model = apps.get_model(*ctype.split(".", 1))
            target = model.objects.get(pk=object_pk)
            view.kwargs["target"] = target
        except (LookupError, TypeError):
            return CommentPostBadRequest(
                "Invalid content_type value: %r" % escape(ctype)
            )
        except AttributeError:
            return CommentPostBadRequest(
                "The given content-type %r does not resolve to a valid model."
                % escape(ctype)
            )
        except ObjectDoesNotExist:
            return CommentPostBadRequest(
                "No object matching content-type %r and object PK %r exists."
                % (escape(ctype), escape(object_pk))
            )
        except (ValueError, ValidationError) as e:
            return CommentPostBadRequest(
                "Attempting to get content-type %r and object PK %r raised %s"
                % (escape(ctype), escape(object_pk), e.__class__.__name__)
            )
        return func(view, *args, **kwargs)

    wrapper.__wrapped__ = func
    return wrapper


class CommentFormTemplateView(TemplateView):
    template_name = "comments/inclusions/_form.html"

    @inject_comment_target
    def get(self, request, *args, **kwargs):
        target = self.kwargs.pop("target")

        context = self.get_context_data(**kwargs)
        context["form"] = get_form()(target)

        return self.render_to_response(context)


class CommentPostView(FormView):
    http_method_names = ["post"]
    template_name = "comments/inclusions/_comment.html"

    def get_form_kwargs(self):
        target = self.kwargs.pop("target")
        data = self.request.POST.copy()
        if not data.get("name", ""):
            data["name"] = self.request.user.name or self.request.user.get_username()
        if not data.get("email", ""):
            data["email"] = self.request.user.email

        return {"target_object": target, "data": data}

    def get_form_class(self):
        return get_form()

    def form_invalid(self, form):
        return CommentPostBadRequest(
            "The comment form failed verification: %s" % escape(str(form.errors))
        )

    def form_valid(self, form):
        request = self.request

        comment = form.get_comment_object(site_id=get_current_site(request).id)
        comment.ip_address = request.META.get("REMOTE_ADDR", None) or None
        comment.user = request.user

        responses = signals.comment_will_be_posted.send(
            sender=comment.__class__, comment=comment, request=request
        )

        for receiver, response in responses:
            if response is False:
                return CommentPostBadRequest(
                    "comment_will_be_posted receiver %r killed the comment"
                    % receiver.__name__
                )

        comment.save()
        signals.comment_was_posted.send(
            sender=comment.__class__, comment=comment, request=request
        )

        context = self.get_context_data(comment=comment, form=form)
        context["is_new"] = True
        return self.render_to_response(context)

    @method_decorator(csrf_protect)
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    @inject_comment_target
    def post(self, request, **kwargs):
        form = self.get_form()

        if form.security_errors():
            return CommentPostBadRequest(
                "The comment form failed security verification: %s"
                % escape(str(form.security_errors()))
            )

        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

dream_blog/core/views.py
from django.core.exceptions import ImproperlyConfigured
from django.utils.encoding import force_str


# Take from https://github.com/brack3t/django-braces
class SetHeadlineMixin:
    """
    Define a `headline` context item as a view attribute
    """

    headline = None  # Default the headline to none

    def get_context_data(self, **kwargs):
        """Add the headline to the context"""
        kwargs = super().get_context_data(**kwargs)
        kwargs.update({"headline": self.get_headline()})
        return kwargs

    def get_headline(self):
        """Fetch the headline from the instance"""
        if self.headline is None:
            class_name = self.__class__.__name__
            raise ImproperlyConfigured(
                f"{class_name} is missing the headline attribute. "
                f"Define {class_name}.headline, or override {class_name}.get_headline()."
            )
        return force_str(self.headline)

dream_blog/notify/views.py
from core.views import SetHeadlineMixin
from notifications.views import AllNotificationsList, UnreadNotificationsList


class AllNotificationsListView(SetHeadlineMixin, AllNotificationsList):
    headline = "全部通知"
    paginate_by = 10
    prefetch_related = ("actor", "target")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["num_all"] = self.request.user.notifications.active().count()
        context["num_unread"] = self.request.user.notifications.unread().count()
        # Add elided page range for pagination template
        if context.get("is_paginated"):
            page_obj = context["page_obj"]
            paginator = context["paginator"]
            context["elided_page_range"] = paginator.get_elided_page_range(
                page_obj.number
            )
        return context


class UnreadNotificationsListView(SetHeadlineMixin, UnreadNotificationsList):
    headline = "未读通知"
    paginate_by = 10
    prefetch_related = ("actor", "target")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["num_all"] = self.request.user.notifications.active().count()
        context["num_unread"] = self.request.user.notifications.unread().count()
        # Add elided page range for pagination template
        if context.get("is_paginated"):
            page_obj = context["page_obj"]
            paginator = context["paginator"]
            context["elided_page_range"] = paginator.get_elided_page_range(
                page_obj.number
            )
        return context

dream_blog/posts/views.py
from core.views import SetHeadlineMixin
from hitcount.views import HitCountDetailView
from posts.models import Post


class PostDetailView(SetHeadlineMixin, HitCountDetailView):
    model = Post
    count_hit = True
    template_name = "posts/detail.html"

    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)
        return response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def get_queryset(self):
        return Post.objects.visible().with_comment_count()

    def get_headline(self):
        return f"{self.object.title} - 追梦人物的博客"

dream_blog/tree_comments/views.py
import functools

import django_comments
from django.apps import apps
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.http.response import HttpResponse as HttpResponse
from django.utils.decorators import method_decorator
from django.utils.html import escape
from django.views.decorators.csrf import csrf_protect
from django.views.generic import FormView, TemplateView
from django_comments import get_form, signals
from django_comments.views.comments import CommentPostBadRequest


def inject_comment_target(func):
    @functools.wraps(func)
    def wrapper(view, *args, **kwargs):
        request = view.request
        if request.method.upper() == "POST":
            ctype = request.POST.get("content_type")
            object_pk = request.POST.get("object_pk")
        else:
            ctype = request.GET.get("content_type")
            object_pk = request.GET.get("object_pk")

        if ctype is None or object_pk is None:
            return CommentPostBadRequest("Missing content_type or object_pk field.")

        try:
            model = apps.get_model(*ctype.split(".", 1))
            target = model.objects.get(pk=object_pk)
            view.kwargs["target"] = target
        except (LookupError, TypeError):
            return CommentPostBadRequest(
                "Invalid content_type value: %r" % escape(ctype)
            )
        except AttributeError:
            return CommentPostBadRequest(
                "The given content-type %r does not resolve to a valid model."
                % escape(ctype)
            )
        except ObjectDoesNotExist:
            return CommentPostBadRequest(
                "No object matching content-type %r and object PK %r exists."
                % (escape(ctype), escape(object_pk))
            )
        except (ValueError, ValidationError) as e:
            return CommentPostBadRequest(
                "Attempting to get content-type %r and object PK %r raised %s"
                % (escape(ctype), escape(object_pk), e.__class__.__name__)
            )
        return func(view, *args, **kwargs)

    wrapper.__wrapped__ = func
    return wrapper


class CommentFormTemplateView(TemplateView):
    template_name = "tree_comments/inclusions/_form.html"

    @inject_comment_target
    def get(self, request, *args, **kwargs):
        target = self.kwargs.pop("target")

        context = self.get_context_data(**kwargs)
        context["form"] = get_form()(target)

        return self.render_to_response(context)


class CommentPostView(FormView):
    http_method_names = ["post"]
    template_name = "tree_comments/inclusions/_comment.html"

    def get_form_kwargs(self):
        target = self.kwargs.pop("target")
        data = self.request.POST.copy()
        if not data.get("name", ""):
            data["name"] = self.request.user.name or self.request.user.get_username()
        if not data.get("email", ""):
            data["email"] = self.request.user.email

        return {"target_object": target, "data": data}

    def get_form_class(self):
        return django_comments.get_form()

    def form_invalid(self, form):
        return CommentPostBadRequest(
            "The comment form failed verification: %s" % escape(str(form.errors))
        )

    def form_valid(self, form):
        request = self.request

        comment = form.get_comment_object(site_id=get_current_site(request).id)
        comment.ip_address = request.META.get("REMOTE_ADDR", None) or None
        comment.user = request.user

        responses = signals.comment_will_be_posted.send(
            sender=comment.__class__, comment=comment, request=request
        )

        for receiver, response in responses:
            if response is False:
                return CommentPostBadRequest(
                    "comment_will_be_posted receiver %r killed the comment"
                    % receiver.__name__
                )

        comment.save()
        signals.comment_was_posted.send(
            sender=comment.__class__, comment=comment, request=request
        )

        context = self.get_context_data(comment=comment, form=form)
        return self.render_to_response(context)

    @method_decorator(csrf_protect)
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    @inject_comment_target
    def post(self, request, **kwargs):
        form = self.get_form()

        if form.security_errors():
            return CommentPostBadRequest(
                "The comment form failed security verification: %s"
                % escape(str(form.security_errors()))
            )

        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

dream_blog/users/views.py
from django.shortcuts import render

# Create your views here.

dream_blog/templates/comments/inclusions/_comment.html
{% load static %}
{# Single comment component with refined avatar and visual hierarchy #}
{# Design intent: Rounded square avatar with subtle ring, clear nesting for replies #}
<div class="mt-5 flex{% if not comment.is_root %} pl-8 md:pl-12 lg:pl-14{% endif %}{% if is_new %} comment-new{% endif %}"
     id="{{ comment.anchor }}">
    {# Refined avatar with rounded square shape and subtle ring #}
    <div class="shrink-0">
        <img class="w-10 h-10 md:w-12 md:h-12 rounded-xl object-cover ring-2 ring-slate-100 dark:ring-slate-700 bg-slate-100 dark:bg-slate-800"
             alt="{{ comment.user.name }}"
             src="{{ comment.user.social_avatar_url }}" />
    </div>
    <div class="ml-3 min-w-0 flex-1">
        {# User info row with reply indicator #}
        <div class="flex items-center gap-2 flex-wrap">
            <span class="text-slate-900 dark:text-slate-100 font-medium">{{ comment.user.name }}</span>
            {% if not comment.is_root %}
                <svg class="w-4 h-4 text-slate-400 dark:text-slate-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 7l5 5m0 0l-5 5m5-5H6"></path>
                </svg>
                <span class="text-slate-600 dark:text-slate-400 text-sm">{{ comment.parent.user.name }}</span>
            {% endif %}
        </div>
        {# Timestamp with subtle styling #}
        <div class="text-xs text-slate-500 dark:text-slate-500 mt-0.5">{{ comment.submit_date | date:"Y-m-d H:i" }}</div>
        {# Comment content with prose styling #}
        <div class="max-w-none prose prose--comment mt-2">
            {{ comment.comment_html | safe }}
        </div>
        {# Action buttons with hover effects #}
        <div class="mt-2 flex items-center gap-3">
            <span class="text-sm text-slate-500 dark:text-slate-400 reply hover:text-cyan-600 dark:hover:text-cyan-400 cursor-pointer transition-colors duration-150"
                  data-cid="{{ comment.pk }}">回复</span>
            <span class="text-sm text-slate-500 dark:text-slate-400 hidden">正在加载评论框...</span>
            <span class="text-sm text-slate-500 dark:text-slate-400 hidden fold hover:text-cyan-600 dark:hover:text-cyan-400 cursor-pointer transition-colors duration-150">收起</span>
        </div>
    </div>
</div>

dream_blog/templates/comments/inclusions/_comment_app.html
{# Comment section header with clean design #}
{# Design intent: No border, natural content separation #}
<div class="flex items-center mt-8 pt-6"
     id="comment-area">
    <span class="font-semibold text-slate-900 dark:text-slate-100">{{ comment_count }} 评论</span>
    {% if user.is_authenticated %}
        <a class="ml-auto text-slate-500 dark:text-slate-400 hover:text-slate-700 dark:hover:text-slate-300"
           href="{% url 'account_logout' %}?next={{ request.get_full_path }}">登出</a>
    {% endif %}
</div>
<div class="mt-4">
    {% if user.is_anonymous %}
        {% include "accounts/inclusions/_login.html" %}
    {% else %}
        {% include "comments/inclusions/_form.html" %}
    {% endif %}
</div>
<div id="comment-list">
    {% if tree_comments %}
        {% for comment in tree_comments %}
            {% include "comments/inclusions/_comment.html" %}
        {% endfor %}
    {% else %}
        <div class="comment-empty">
            <svg class="comment-empty__icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z"></path>
            </svg>
            <p class="comment-empty__text">暂无评论，来抢沙发吧！</p>
        </div>
    {% endif %}
</div>

dream_blog/templates/comments/inclusions/_form.html
{% load static %}
{# Comment form with enhanced styling and focus states #}
{# Design intent: Clean form layout with visual feedback on interactions #}
<form action="{% url "comments:post" %}" method="post" class="comment-form">
    {% csrf_token %}
    {% for hidden in form.hidden_fields %}{{ hidden }}{% endfor %}
    <div class="flex gap-3">
        {# User avatar with refined styling #}
        <div class="shrink-0">
            <img class="comment-avatar"
                 alt="{{ user.name|default:'User' }}"
                 src="{{ user.social_avatar_url }}" />
        </div>
        <div class="min-w-0 flex-1">
            {# Textarea with enhanced focus ring and placeholder #}
            <textarea rows="4"
                      class="textarea"
                      name="{{ form.comment.html_name }}"
                      id="{{ form.comment.id_for_label }}"
                      placeholder="留下你的评论..."
                      required></textarea>
            <div class="mt-3 flex items-center justify-between">
                {# Markdown hint with official Markdown logo #}
                <div class="flex items-center gap-1.5 text-slate-500 dark:text-slate-400">
                    <img class="w-4 h-4" src="{% static 'markdown-fill.svg' %}" alt="Markdown">
                    <span class="text-xs">支持 Markdown 语法</span>
                </div>
                {# Submit button with primary styling #}
                <button class="btn--primary btn--sm" type="submit">
                    提交评论
                </button>
            </div>
        </div>
    </div>
</form>