config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.views import defaults as default_views

from dream_blog.feeds import RssFeed
from dream_blog.sitemaps import SITEMAPS

urlpatterns = [
    path("sitemap.xml", sitemap, {"sitemaps": SITEMAPS}, name="sitemap"),
    path("rss.xml", RssFeed(), name="rss"),
    path("", include("dream_blog.urls")),
    path("posts/", include("posts.urls")),
    path("tutorials/", include("tutorials.urls")),
    path("columns/", include("columns.urls")),
    path("comments/", include("comments.urls")),
    path("accounts/", include("allauth.urls")),
    path("markdown-field/", include("markdown_field.urls")),
    path("ht/", include("health_check.urls")),
    path("webtools/", include("webtools.urls")),
    path("notifications/", include("notify.urls")),
    path("notifications/", include("notifications.urls")),
    path(settings.ADMIN_URL, admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

    if "django_browser_reload" in settings.INSTALLED_APPS:
        urlpatterns = [
            path("__reload__/", include("django_browser_reload.urls"))
        ] + urlpatterns

dream_blog/notify/urls.py
from django.urls import path

from . import views

app_name = "notify"
urlpatterns = [
    path("", views.AllNotificationsListView.as_view(), name="notification_all"),
    path(
        "unread/",
        views.UnreadNotificationsListView.as_view(),
        name="notification_unread",
    ),
]

dream_blog/posts/urls.py
from django.urls import path
from posts import views

app_name = "posts"
urlpatterns = [
    path("<int:pk>/", views.PostDetailView.as_view(), name="detail"),
]

dream_blog/urls.py
from django.urls import path

from dream_blog.views import HomeView

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
]

dream_blog/webtools/models.py
# Webtools has no models - it's a utility app

dream_blog/columns/views.py
from columns.models import Article, Column
from core.views import SetHeadlineMixin
from hitcount.views import HitCountDetailView


class ColumnDetailView(SetHeadlineMixin, HitCountDetailView):
    model = Column
    count_hit = True
    template_name = "columns/detail.html"

    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)
        return response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        articles = self.object.article_set.visible().order_by("-publish_date")
        context["articles"] = articles
        return context

    def get_queryset(self):
        return Column.objects.visible().order_by("-created_at")

    def get_headline(self):
        return self.object.title


class ArticleDetailView(SetHeadlineMixin, HitCountDetailView):
    model = Article
    count_hit = True
    template_name = "columns/article_detail.html"

    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)
        return response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def get_queryset(self):
        return (
            Article.objects.visible()
            .select_related("column")
            .order_by("-publish_date")
            .with_comment_count()
        )

    def get_headline(self):
        return f"{self.object.title} - {self.object.column.title}"

dream_blog/comments/views.py
import functools

from comments import get_form
from django.apps import apps
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.http.response import HttpResponse as HttpResponse
from django.utils.decorators import method_decorator
from django.utils.html import escape
from django.views.decorators.csrf import csrf_protect
from django.views.generic import FormView, TemplateView
from tree_comments import signals
from tree_comments.views import CommentPostBadRequest


def inject_comment_target(func):
    @functools.wraps(func)
    def wrapper(view, *args, **kwargs):
        request = view.request
        if request.method.upper() == "POST":
            ctype = request.POST.get("content_type")
            object_pk = request.POST.get("object_pk")
        else:
            ctype = request.GET.get("content_type")
            object_pk = request.GET.get("object_pk")

        if ctype is None or object_pk is None:
            return CommentPostBadRequest("Missing content_type or object_pk field.")

        try:
            model = apps.get_model(*ctype.split(".", 1))
            target = model.objects.get(pk=object_pk)
            view.kwargs["target"] = target
        except (LookupError, TypeError):
            return CommentPostBadRequest(
                "Invalid content_type value: %r" % escape(ctype)
            )
        except AttributeError:
            return CommentPostBadRequest(
                "The given content-type %r does not resolve to a valid model."
                % escape(ctype)
            )
        except ObjectDoesNotExist:
            return CommentPostBadRequest(
                "No object matching content-type %r and object PK %r exists."
                % (escape(ctype), escape(object_pk))
            )
        except (ValueError, ValidationError) as e:
            return CommentPostBadRequest(
                "Attempting to get content-type %r and object PK %r raised %s"
                % (escape(ctype), escape(object_pk), e.__class__.__name__)
            )
        return func(view, *args, **kwargs)

    wrapper.__wrapped__ = func
    return wrapper


class CommentFormTemplateView(TemplateView):
    template_name = "comments/inclusions/_form.html"

    @inject_comment_target
    def get(self, request, *args, **kwargs):
        target = self.kwargs.pop("target")

        context = self.get_context_data(**kwargs)
        context["form"] = get_form()(target)

        return self.render_to_response(context)


class CommentPostView(FormView):
    http_method_names = ["post"]
    template_name = "comments/inclusions/_comment.html"

    def get_form_kwargs(self):
        target = self.kwargs.pop("target")
        data = self.request.POST.copy()
        if not data.get("name", ""):
            data["name"] = self.request.user.name or self.request.user.get_username()
        if not data.get("email", ""):
            data["email"] = self.request.user.email

        return {"target_object": target, "data": data}

    def get_form_class(self):
        return get_form()

    def form_invalid(self, form):
        return CommentPostBadRequest(
            "The comment form failed verification: %s" % escape(str(form.errors))
        )

    def form_valid(self, form):
        request = self.request

        comment = form.get_comment_object(site_id=get_current_site(request).id)
        comment.ip_address = request.META.get("REMOTE_ADDR", None) or None
        comment.user = request.user

        responses = signals.comment_will_be_posted.send(
            sender=comment.__class__, comment=comment, request=request
        )

        for receiver, response in responses:
            if response is False:
                return CommentPostBadRequest(
                    "comment_will_be_posted receiver %r killed the comment"
                    % receiver.__name__
                )

        comment.save()
        signals.comment_was_posted.send(
            sender=comment.__class__, comment=comment, request=request
        )

        context = self.get_context_data(comment=comment, form=form)
        context["is_new"] = True
        return self.render_to_response(context)

    @method_decorator(csrf_protect)
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    @inject_comment_target
    def post(self, request, **kwargs):
        form = self.get_form()

        if form.security_errors():
            return CommentPostBadRequest(
                "The comment form failed security verification: %s"
                % escape(str(form.security_errors()))
            )

        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

dream_blog/core/views.py
from django.core.exceptions import ImproperlyConfigured
from django.utils.encoding import force_str


# Take from https://github.com/brack3t/django-braces
class SetHeadlineMixin:
    """
    Define a `headline` context item as a view attribute
    """

    headline = None  # Default the headline to none

    def get_context_data(self, **kwargs):
        """Add the headline to the context"""
        kwargs = super().get_context_data(**kwargs)
        kwargs.update({"headline": self.get_headline()})
        return kwargs

    def get_headline(self):
        """Fetch the headline from the instance"""
        if self.headline is None:
            class_name = self.__class__.__name__
            raise ImproperlyConfigured(
                f"{class_name} is missing the headline attribute. "
                f"Define {class_name}.headline, or override {class_name}.get_headline()."
            )
        return force_str(self.headline)

dream_blog/notify/views.py
from core.views import SetHeadlineMixin
from notifications.views import AllNotificationsList, UnreadNotificationsList


class AllNotificationsListView(SetHeadlineMixin, AllNotificationsList):
    headline = "全部通知"
    paginate_by = 10
    prefetch_related = ("actor", "target")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["num_all"] = self.request.user.notifications.active().count()
        context["num_unread"] = self.request.user.notifications.unread().count()
        # Add elided page range for pagination template
        if context.get("is_paginated"):
            page_obj = context["page_obj"]
            paginator = context["paginator"]
            context["elided_page_range"] = paginator.get_elided_page_range(
                page_obj.number
            )
        return context


class UnreadNotificationsListView(SetHeadlineMixin, UnreadNotificationsList):
    headline = "未读通知"
    paginate_by = 10
    prefetch_related = ("actor", "target")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["num_all"] = self.request.user.notifications.active().count()
        context["num_unread"] = self.request.user.notifications.unread().count()
        # Add elided page range for pagination template
        if context.get("is_paginated"):
            page_obj = context["page_obj"]
            paginator = context["paginator"]
            context["elided_page_range"] = paginator.get_elided_page_range(
                page_obj.number
            )
        return context

dream_blog/posts/views.py
from core.views import SetHeadlineMixin
from hitcount.views import HitCountDetailView
from posts.models import Post


class PostDetailView(SetHeadlineMixin, HitCountDetailView):
    model = Post
    count_hit = True
    template_name = "posts/detail.html"

    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)
        return response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def get_queryset(self):
        return Post.objects.visible().with_comment_count()

    def get_headline(self):
        return f"{self.object.title} - 追梦人物的博客"

dream_blog/tree_comments/views.py
import functools

import django_comments
from django.apps import apps
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.http.response import HttpResponse as HttpResponse
from django.utils.decorators import method_decorator
from django.utils.html import escape
from django.views.decorators.csrf import csrf_protect
from django.views.generic import FormView, TemplateView
from django_comments import get_form, signals
from django_comments.views.comments import CommentPostBadRequest


def inject_comment_target(func):
    @functools.wraps(func)
    def wrapper(view, *args, **kwargs):
        request = view.request
        if request.method.upper() == "POST":
            ctype = request.POST.get("content_type")
            object_pk = request.POST.get("object_pk")
        else:
            ctype = request.GET.get("content_type")
            object_pk = request.GET.get("object_pk")

        if ctype is None or object_pk is None:
            return CommentPostBadRequest("Missing content_type or object_pk field.")

        try:
            model = apps.get_model(*ctype.split(".", 1))
            target = model.objects.get(pk=object_pk)
            view.kwargs["target"] = target
        except (LookupError, TypeError):
            return CommentPostBadRequest(
                "Invalid content_type value: %r" % escape(ctype)
            )
        except AttributeError:
            return CommentPostBadRequest(
                "The given content-type %r does not resolve to a valid model."
                % escape(ctype)
            )
        except ObjectDoesNotExist:
            return CommentPostBadRequest(
                "No object matching content-type %r and object PK %r exists."
                % (escape(ctype), escape(object_pk))
            )
        except (ValueError, ValidationError) as e:
            return CommentPostBadRequest(
                "Attempting to get content-type %r and object PK %r raised %s"
                % (escape(ctype), escape(object_pk), e.__class__.__name__)
            )
        return func(view, *args, **kwargs)

    wrapper.__wrapped__ = func
    return wrapper


class CommentFormTemplateView(TemplateView):
    template_name = "tree_comments/inclusions/_form.html"

    @inject_comment_target
    def get(self, request, *args, **kwargs):
        target = self.kwargs.pop("target")

        context = self.get_context_data(**kwargs)
        context["form"] = get_form()(target)

        return self.render_to_response(context)


class CommentPostView(FormView):
    http_method_names = ["post"]
    template_name = "tree_comments/inclusions/_comment.html"

    def get_form_kwargs(self):
        target = self.kwargs.pop("target")
        data = self.request.POST.copy()
        if not data.get("name", ""):
            data["name"] = self.request.user.name or self.request.user.get_username()
        if not data.get("email", ""):
            data["email"] = self.request.user.email

        return {"target_object": target, "data": data}

    def get_form_class(self):
        return django_comments.get_form()

    def form_invalid(self, form):
        return CommentPostBadRequest(
            "The comment form failed verification: %s" % escape(str(form.errors))
        )

    def form_valid(self, form):
        request = self.request

        comment = form.get_comment_object(site_id=get_current_site(request).id)
        comment.ip_address = request.META.get("REMOTE_ADDR", None) or None
        comment.user = request.user

        responses = signals.comment_will_be_posted.send(
            sender=comment.__class__, comment=comment, request=request
        )

        for receiver, response in responses:
            if response is False:
                return CommentPostBadRequest(
                    "comment_will_be_posted receiver %r killed the comment"
                    % receiver.__name__
                )

        comment.save()
        signals.comment_was_posted.send(
            sender=comment.__class__, comment=comment, request=request
        )

        context = self.get_context_data(comment=comment, form=form)
        return self.render_to_response(context)

    @method_decorator(csrf_protect)
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    @inject_comment_target
    def post(self, request, **kwargs):
        form = self.get_form()

        if form.security_errors():
            return CommentPostBadRequest(
                "The comment form failed security verification: %s"
                % escape(str(form.security_errors()))
            )

        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

dream_blog/users/views.py
from django.shortcuts import render

# Create your views here.

dream_blog/templates/inclusions/_entry_content.html
{# Entry content wrapper with prose styling #}
{# No max-width constraint: content fills available space naturally #}
<div class="mt-10 prose w-full max-w-none" id="content">
  {{ entry.content_html | safe }}
  <p class="text-center dark:text-slate-400">-- EOF --</p>
</div>

dream_blog/templates/inclusions/_entry_meta.html
{# Entry meta info: date, views, comments with slate color scheme #}
<div class="text-slate-500 dark:text-slate-400 text-sm mt-3">
  <span class="after:content-['•'] after:mx-1 text-slate-700 dark:text-slate-400">{{ entry.publish_date | date:"Y-m-d" }}</span><span class="after:content-['•'] after:mx-1 text-slate-700 dark:text-slate-400">{{ entry.hit_count.hits }} 阅读</span><a href="{{ entry.get_absolute_url }}#comment-area" class="text-slate-700 dark:text-slate-400 hover:text-cyan-600 dark:hover:text-cyan-400">{{ entry.num_comments }} 评论</a>
</div>

dream_blog/templates/inclusions/_entry_meta_index.html
{% load entry_urls %}
{# Entry meta info for index pages: date, views, comments with dot separators #}
{# Design intent: Compact layout with clear visual separation using dot separators #}
<div class="text-slate-500 dark:text-slate-400 text-sm mt-3">
  <span class="after:content-['•'] after:mx-1 text-slate-700 dark:text-slate-400">{{ entry.pub_date|date:"Y-m-d" }}</span><span class="after:content-['•'] after:mx-1 text-slate-700 dark:text-slate-400">{{ entry.views|default:0 }} 阅读</span><a href="{{ entry|entry_url }}#comment-area"
     class="text-slate-700 dark:text-slate-400 hover:text-cyan-600 dark:hover:text-cyan-400 transition-colors duration-150">{{ entry.comment_count }} 评论</a>
</div>

dream_blog/templates/inclusions/_footer.html
{# Site footer: copyright and links with slate color scheme #}
<footer class="text-sm text-slate-500 dark:text-slate-400 my-10">
  <div class="flex justify-center">
    <a href="https://beian.miit.gov.cn/" target="_blank" class="hover:text-slate-700 dark:hover:text-slate-200 transition-colors">浙ICP备2020042435号-1</a>
  </div>
  <div class="flex justify-center">
    <span class="mr-2">Copyright © 2024</span><span>追梦人物的博客</span>
    <a class="ml-2 text-slate-500 dark:text-slate-400 hover:text-slate-700 dark:hover:text-slate-200 transition-colors"
       href="https://github.com/jukanntenn/django-dream-blog"
       target="_blank">博客源码</a>
  </div>
  <div class="flex justify-center space-x-3">
    <a class="hover:text-slate-700 dark:hover:text-slate-200 transition-colors"
       href="{% url 'sitemap' %}">Sitemap</a>
    <a class="hover:text-slate-700 dark:hover:text-slate-200 transition-colors"
       href="{% url 'rss' %}">RSS</a>
  </div>
</footer>

dream_blog/templates/inclusions/_nav.html
{% load static %}
{% load notifications_tags %}
{# Navigation bar: sticky header with theme switcher #}
{# Design intent: Transparent background to show gradient, no border for natural layout #}
<div id="site-nav"
     class="sticky top-0 z-[60] w-full flex-none transition-all duration-300"
     data-blur-nav>
  <div class="max-w-[90rem] mx-auto px-4 lg:px-8">
    <div class="py-4">
      <div class="relative flex items-center justify-between">
        <div class="flex items-center">
          <span class="inline-block lg:hidden" id="offcanvas-trigger">
            <img class="dark:invert" height="20" width="20" src="{% static 'menu-fill.svg' %}" />
          </span>
          <a href="{% url 'home' %}"
             class="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 lg:static lg:translate-x-0 lg:translate-y-0">
            <span class="text-3xl whitespace-nowrap">🦋</span>
          </a>
        </div>
        <div class="flex items-center gap-2">
          <!-- Theme switcher button with slate hover state -->
          <button id="theme-switcher"
                  class="p-2 rounded-lg hover:bg-slate-100/80 dark:hover:bg-slate-800/50 transition-colors"
                  aria-label="切换主题">
            <img data-theme-icon="light"
                 height="20"
                 width="20"
                 src="{% static 'sun-fill.svg' %}"
                 alt="亮色模式"
                 class="dark:invert hidden" />
            <img data-theme-icon="dark"
                 height="20"
                 width="20"
                 src="{% static 'moon-line.svg' %}"
                 alt="暗色模式"
                 class="dark:invert hidden" />
            <img data-theme-icon="system"
                 height="20"
                 width="20"
                 src="{% static 'contrast-fill.svg' %}"
                 alt="跟随系统"
                 class="dark:invert hidden" />
          </button>
          {% if user.is_authenticated %}
            {% notifications_unread as num_unread %}
            <a href="{% url 'notify:notification_all' %}"
               class="p-2 rounded-lg hover:bg-slate-100/80 dark:hover:bg-slate-800/50 transition-colors relative"
               aria-label="通知">
              <img class="dark:invert{% if num_unread != 0 %} text-cyan-600 dark:text-cyan-400{% endif %}" height="20" width="20" src="{% static 'notification-4-line.svg' %}" alt="通知" />
              {% if num_unread != 0 %}
                <span class="absolute -top-1.5 -right-1.5 flex h-4 min-w-4 items-center justify-center rounded-full bg-cyan-600 dark:bg-cyan-400 px-1 text-[10px] font-bold text-white dark:text-slate-900">
                  {% if num_unread > 99 %}99+{% else %}{{ num_unread }}{% endif %}
                </span>
              {% endif %}
            </a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>

dream_blog/templates/inclusions/_pagination.html
{% load static %}
{# Pagination component with enhanced visual feedback #}
{# Design intent: Clear active state, smooth hover transitions #}
<nav aria-label="Pagination" class="flex items-center gap-1">
  {# Previous page button #}
  {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}"
       class="p-2 rounded-lg text-slate-600 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800 hover:text-slate-900 dark:hover:text-slate-100 transition-all duration-150">
      <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path>
      </svg>
    </a>
  {% else %}
    <span class="p-2 rounded-lg text-slate-300 dark:text-slate-600 cursor-not-allowed">
      <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path>
      </svg>
    </span>
  {% endif %}

  {# Page numbers #}
  {% for number in elided_page_range %}
    {% if number == page_obj.number %}
      <span class="pagination-item--active">{{ number }}</span>
    {% elif number == paginator.ELLIPSIS %}
      <span class="px-3 py-2 text-slate-400 dark:text-slate-500">{{ number }}</span>
    {% else %}
      <a href="?page={{ number }}" class="pagination-item">{{ number }}</a>
    {% endif %}
  {% endfor %}

  {# Next page button #}
  {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}"
       class="p-2 rounded-lg text-slate-600 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800 hover:text-slate-900 dark:hover:text-slate-100 transition-all duration-150">
      <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path>
      </svg>
    </a>
  {% else %}
    <span class="p-2 rounded-lg text-slate-300 dark:text-slate-600 cursor-not-allowed">
      <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path>
      </svg>
    </span>
  {% endif %}
</nav>

dream_blog/templates/inclusions/_prev_next.html
<div class="flex flex-wrap justify-between gap-4 pt-6 mt-8">
    {% if entry.prev %}
        <div class="flex min-w-[16rem] flex-1">
            <a class="nav-prev-next group inline-flex max-w-full min-w-0 items-center gap-1"
               href="{{ entry.prev.get_absolute_url }}">
                <svg class="h-4 w-4 text-slate-500 transition-colors group-hover:text-cyan-600 dark:text-slate-400 dark:group-hover:text-cyan-400"
                     fill="none"
                     stroke="currentColor"
                     viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path>
                </svg>
                <span class="text-xs text-slate-500 transition-colors group-hover:text-cyan-600 dark:text-slate-400 dark:group-hover:text-cyan-400">上一篇</span>
                <span class="min-w-0 max-w-[28ch] truncate text-sm font-medium text-slate-700 dark:text-slate-300">{{ entry.prev.title }}</span>
            </a>
        </div>
    {% else %}
        <div class="flex-1"></div>
    {% endif %}

    {% if entry.next %}
        <div class="flex min-w-[16rem] flex-1 justify-end">
            <a class="nav-prev-next group inline-flex max-w-full min-w-0 items-center gap-1"
               href="{{ entry.next.get_absolute_url }}">
                <span class="min-w-0 max-w-[28ch] truncate text-sm font-medium text-slate-700 dark:text-slate-300">{{ entry.next.title }}</span>
                <span class="text-xs text-slate-500 transition-colors group-hover:text-cyan-600 dark:text-slate-400 dark:group-hover:text-cyan-400">下一篇</span>
                <svg class="h-4 w-4 text-slate-500 transition-colors group-hover:text-cyan-600 dark:text-slate-400 dark:group-hover:text-cyan-400"
                     fill="none"
                     stroke="currentColor"
                     viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path>
                </svg>
            </a>
        </div>
    {% else %}
        <div class="flex-1"></div>
    {% endif %}
</div>

dream_blog/templates/inclusions/_profile.html
{% load static %}
{# Profile sidebar: blogger info and social links #}
{# Design intent: Natural content flow - no wrapper card, content forms its own visual block #}
<div class="space-y-3">
  {# Blogger name and badge - clean layout without avatar #}
  <div class="flex items-center gap-2">
    <span class="text-lg font-semibold text-slate-900 dark:text-slate-100">{{ profile.blogger }}</span>
    <span class="badge--success text-xs">博主</span>
  </div>

  {# Slogan with comfortable leading and subtle color #}
  <div class="text-sm text-slate-600 dark:text-slate-400 leading-relaxed">{{ profile.slogan }}</div>

  {# Social links with hover feedback #}
  <div class="flex items-center gap-3">
    {% for slink in profile.social_links %}
      {% if slink.url %}
        <a class="p-1.5 rounded-lg hover:bg-slate-200/80 dark:hover:bg-slate-700/50 transition-colors duration-150"
           href="{{ slink.url }}"
           target="_blank"
           rel="noopener noreferrer"
           aria-label="{{ slink.name|default:'Social link' }}">
          <img class="dark:invert w-5 h-5" alt="{{ slink.name|default:'Social icon' }}" height="20" width="20" src="{% static slink.icon %}" />
        </a>
      {% endif %}
    {% endfor %}
  </div>
</div>

dream_blog/templates/inclusions/_toc.html
{% if toc %}
  <div>
    <h3 class="sidebar-title">目录</h3>
    <div class="toc" id="toc">
      <ul>
        {{ toc | safe }}
      </ul>
    </div>
  </div>
{% endif %}